matrix:
  include:
    - language: node_js
      node_js:
        - 10
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - npm install -g @commitlint/travis-cli

      install:
        - npm install
        - npm install -g codecov
        - npm install -g eslint
        - commitlint-travis

      script:
        - codecov
      cache:
        directories:
          - node_modules

    - language: elixir
      elixir:
        - 1.6.6
      otp_release:
        - 21.0
      addons:
        postgresql: '9.4'

      install:
        - mix local.rebar --force
        - mix local.hex --force;

      before_script:
        - sudo chown -R travis ./travis/pull_server.sh
        - sudo chmod +x ./travis/pull_server.sh
        - ./travis/pull_server.sh
      cache:
        directories:
          - _build
          - deps

notifications:
  email:
    on_failure: change

# after_success: 'npm run coveralls'
