language: elixir
elixir:
  - 1.6.6
otp_release:
  - 21.0
addons:
  postgresql: '9.4'

before_install:
  - sudo chown -R travis ./travis/install_node.sh
  - sudo chmod +x ./travis/install_node.sh
  - ./travis/install_node.sh
  - npm install -g @commitlint/travis-cli

install:
  - npm install
  - npm install -g codecov
  - npm install -g eslint
  - commitlint-travis
  - mix local.rebar --force
  - mix local.hex --force

script:
  - codecov

before_script:
  - sudo chown -R travis ./travis/pull_server.sh
  - sudo chmod +x ./travis/pull_server.sh
  - ./travis/pull_server.sh

cache:
  directories:
    - node_modules
    - _build
    - dep

notifications:
  email:
    on_failure: change

# after_success: 'npm run coveralls'
