language: node_js

node_js:
  - 10

before_script:
  - echo "before_script"
  - git clone https://github.com/coderplanets/coderplanets_server.git
  - ls coderplanets_server

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @commitlint/travis-cli

install:
  - npm install
  - npm install -g codecov
  - npm install -g eslint
  - commitlint-travis

script:
  - codecov

notifications:
  email:
    on_failure: change

# after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
